services:
  server:
    image: andresgzz/server:latest
    build:
      context: .
    ports:
      - "8082:8082"   # Cambiado para mapear el puerto 8082 del contenedor al 8082 del host

    depends_on:
      - db

    pull_policy: never
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1216
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SERVER_PORT: "8082"
    networks:
      - app-network
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1216
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
