version: '3'
services:
  server:
    image: andresgzz/server:latest
    build:
      context: .
    ports:
      - "8082:8082" # This will be mapped as a NodePort service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1216
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SERVER_PORT: "8082"
    networks:
      - app-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1216
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090" # This will be mapped as a NodePort service
    volumes:
      - .\prometheus.yml:\etc\prometheus\prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000" # This will be mapped as a NodePort service
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
