apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: wrouesnel/postgres_exporter
          args:
            - "--extend.query-path=/etc/postgres_exporter/queries.yaml"
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:1216@db:5432/store?sslmode=disable"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/postgres_exporter
      volumes:
        - name: config-volume
          configMap:
            name: postgres-exporter-config